version: "3.8"

services:
  db:
    image: mongo:4.1.8-xenial
    container_name: <project>_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<project>
      - MONGO_INITDB_ROOT_PASSWORD=<project>
    volumes:
      - <project>_dbdata:/data/db
    expose: 
      - 27017
  
  redis :
    restart: unless-stopped
    image : redis:alpine
    container_name: <project>_cache
    expose :
      - 6379

  web:
    build: .
    image: node:12.13.0-alpine
    container_name: <project>_web
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=<project>
      - MONGO_PASSWORD=<project>
      - MONGO_HOSTNAME=<project>_db
      - MONGO_PORT=27017
      - MONGO_DB=<project>
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/<project>
      - VIRTUAL_PROTO=http
#     - lETSENCRYPT_EMAIL=
#     - LETSENCRYPT_HOST=
    expose:
      - 3000
    volumes:
      - .:/code
    command: sh -c "/entrypoint_node" 
    

volumes:
  <project>_dbdata:

networks: 
  external: 
    nginx-proxy: